import React, { useState } from 'react';
import {
  ReceiptText,
  Save,
  Trash2,
  XCircle,
  HelpCircle,
  MessageCircle,
  Barcode,
  Coins,
  Printer,
  Sliders,
  User,
  FileCheck
} from 'lucide-react';
import { formatCurrency, formatWeight, calculateTaxes, roundTo } from '../../utils/calculations';
import { PrintVoucherModal } from '../common/PrintVoucherModal';
import { WhatsAppShareModal } from '../common/WhatsAppShareModal';
import { FieldHelpModal } from '../common/FieldHelpModal';
import { ColumnSettingsModal } from '../common/ColumnSettingsModal';
import { ColumnSetting } from '../../types/erp';
import { useTheme } from '../../context/ThemeContext';

interface SalesInvoiceViewProps {
  onClose: () => void;
  goldRate: number;
}

const DEFAULT_SALES_COLUMNS: ColumnSetting[] = [
  { id: 'item_name', label: 'Item Name', visible: true, width: 220, order: 0 },
  { id: 'gross_wt', label: 'Gross Wt', visible: true, width: 90, order: 1 },
  { id: 'net_wt', label: 'Net Wt', visible: true, width: 90, order: 2 },
  { id: 'purity', label: 'Purity', visible: true, width: 70, order: 3 },
  { id: 'rate', label: 'Rate/Gm', visible: true, width: 90, order: 4 },
  { id: 'making', label: 'Making', visible: true, width: 90, order: 5 },
  { id: 'total_amt', label: 'Total Amount', visible: true, width: 120, order: 6 },
];

export const SalesInvoiceView: React.FC<SalesInvoiceViewProps> = ({ onClose, goldRate }) => {
  const { currentTheme, isDark } = useTheme();

  // Invoice Mode: Tax Invoice vs Estimate / Quotation
  const [billMode, setBillMode] = useState<'Tax Invoice' | 'Estimate'>('Tax Invoice');
  const [salesmanName, setSalesmanName] = useState('Pooja Sharma (EMP-204)');
  const [customerName, setCustomerName] = useState('Walk-in Customer');
  const [phone, setPhone] = useState('9820123456');
  const [invoiceNo, setInvoiceNo] = useState(`INV-2026-${Math.floor(100 + Math.random() * 900)}`);
  const [invoiceDate, setInvoiceDate] = useState(new Date().toISOString().split('T')[0]);
  const [barcodeInput, setBarcodeInput] = useState('');

  const [items, setItems] = useState([
    {
      id: 'it-1',
      item_name: '22K 916 Royal Peacock Choker Necklace',
      gross_wt: 32.500,
      black_beats: 0,
      stone_wt: 1.200,
      net_wt: 31.300,
      purity: 91.6,
      rate: goldRate,
      making_per_gm: 450,
      making_amt: 14085,
      hallmark_charges: 45,
      total_amt: 241010,
    },
  ]);

  const [urdAmount, setUrdAmount] = useState(15000);
  const [discount, setDiscount] = useState(1010);
  const [cashTendered, setCashTendered] = useState(25000);
  const [bankTendered, setBankTendered] = useState(200000);

  // Modals
  const [showPrint, setShowPrint] = useState(false);
  const [showWhatsApp, setShowWhatsApp] = useState(false);
  const [showHelp, setShowHelp] = useState(false);
  const [columns, setColumns] = useState<ColumnSetting[]>(DEFAULT_SALES_COLUMNS);
  const [showColumnSettings, setShowColumnSettings] = useState(false);

  const subtotal = items.reduce((s, it) => s + it.total_amt, 0);
  const gstRate = billMode === 'Tax Invoice' ? 3.0 : 0.0;
  const taxes = calculateTaxes(subtotal, false, gstRate);
  const totalBill = subtotal + taxes.gstAmt - discount;
  const netDue = Math.max(0, roundTo(totalBill - urdAmount - cashTendered - bankTendered, 2));

  const handleScanBarcode = (e: React.FormEvent) => {
    e.preventDefault();
    if (!barcodeInput.trim()) return;
    const newItem = {
      id: `it-${Date.now()}`,
      item_name: `Tagged Ornament (${barcodeInput.toUpperCase()})`,
      gross_wt: 15.000,
      black_beats: 0,
      stone_wt: 0,
      net_wt: 15.000,
      purity: 91.6,
      rate: goldRate,
      making_per_gm: 400,
      making_amt: 6000,
      hallmark_charges: 45,
      total_amt: roundTo(15.0 * goldRate + 6000 + 45, 2),
    };
    setItems([...items, newItem]);
    setBarcodeInput('');
  };

  const handleSave = () => {
    alert(`${billMode} ${invoiceNo} generated by ${salesmanName} for ₹${totalBill.toLocaleString('en-IN')}!`);
    onClose();
  };

  return (
    <div className="space-y-4 animate-in fade-in duration-200">
      {/* Header */}
      <div className={`${currentTheme.cardBg} border ${currentTheme.cardBorder} rounded-xl p-3.5 flex flex-wrap items-center justify-between gap-3 shadow-sm`}>
        <div className="flex items-center space-x-3">
          <div className="p-2 rounded-lg bg-emerald-50 text-emerald-600 border border-emerald-200">
            <ReceiptText className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center space-x-2">
              <h1 className="text-base font-bold text-slate-800">Sales Invoice & POS Billing</h1>
              <span className={`text-xs px-2 py-0.5 rounded font-mono font-bold border ${
                billMode === 'Tax Invoice' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' : 'bg-amber-50 text-amber-800 border-amber-300'
              }`}>
                {billMode} • {invoiceNo}
              </span>
            </div>
            <p className="text-xs text-slate-500">
              Counter POS billing, barcode scanner input, URD exchange credit, and salesman tracking.
            </p>
          </div>
        </div>

        <div className="flex items-center space-x-2 flex-wrap">
          <button
            onClick={() => setShowColumnSettings(true)}
            className="flex items-center space-x-1 px-2.5 py-1.5 rounded-lg bg-slate-100 text-slate-700 text-xs font-mono font-bold border border-slate-200 hover:bg-slate-200 cursor-pointer"
            title="Grid Settings"
          >
            <Sliders className="w-3.5 h-3.5 text-blue-600" />
            <span>GS</span>
          </button>

          <button
            onClick={handleSave}
            className="flex items-center space-x-1 px-4 py-1.5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold shadow cursor-pointer"
          >
            <Save className="w-3.5 h-3.5" />
            <span>Save & Settle</span>
          </button>

          <button
            onClick={() => setShowPrint(true)}
            className="flex items-center space-x-1 px-3 py-1.5 rounded-lg bg-slate-100 text-slate-700 text-xs font-semibold border border-slate-200 hover:bg-slate-200 cursor-pointer"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print Bill</span>
          </button>

          <button
            onClick={() => setShowWhatsApp(true)}
            className="flex items-center space-x-1 px-3 py-1.5 rounded-lg bg-emerald-50 text-emerald-700 text-xs font-semibold border border-emerald-200 hover:bg-emerald-100 cursor-pointer"
          >
            <MessageCircle className="w-3.5 h-3.5" />
            <span>WhatsApp</span>
          </button>

          <button
            onClick={() => setShowHelp(true)}
            className="p-1.5 rounded-lg bg-amber-50 text-amber-800 text-xs font-bold border border-amber-300 hover:bg-amber-100 cursor-pointer"
          >
            <HelpCircle className="w-3.5 h-3.5" />
          </button>

          <button onClick={onClose} className="p-1.5 text-slate-400 hover:text-slate-600 cursor-pointer">
            <XCircle className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Bill Controls Strip: Tax Invoice vs Estimate & Salesman Name */}
      <div className={`border rounded-xl p-4 shadow-sm grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-4 text-xs transition-all ${
        isDark ? 'bg-[#0f172a]/90 border-white/10 text-white' : 'bg-white border-sky-200/80 text-slate-800'
      }`}>
        {/* Bill Type Mode Selection */}
        <div>
          <label className={`block text-[11px] font-bold mb-1 ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
            Invoice Mode <span className="text-rose-500">*</span>
          </label>
          <div className="grid grid-cols-2 gap-2">
            <button
              type="button"
              onClick={() => setBillMode('Tax Invoice')}
              className={`py-1.5 rounded-lg font-bold border transition-all cursor-pointer ${
                billMode === 'Tax Invoice'
                  ? isDark
                    ? 'bg-emerald-500/20 border-emerald-400 text-emerald-300 shadow-2xs'
                    : 'bg-emerald-50 border-emerald-400 text-emerald-800 shadow-2xs'
                  : isDark
                  ? 'bg-white/5 border-white/10 text-slate-400 hover:bg-white/10'
                  : 'bg-slate-50 border-slate-200 text-slate-600'
              }`}
            >
              Tax Invoice (3% GST)
            </button>
            <button
              type="button"
              onClick={() => setBillMode('Estimate')}
              className={`py-1.5 rounded-lg font-bold border transition-all cursor-pointer ${
                billMode === 'Estimate'
                  ? isDark
                    ? 'bg-amber-400/20 border-amber-400 text-amber-300 shadow-2xs'
                    : 'bg-amber-50 border-amber-400 text-amber-800 shadow-2xs'
                  : isDark
                  ? 'bg-white/5 border-white/10 text-slate-400 hover:bg-white/10'
                  : 'bg-slate-50 border-slate-200 text-slate-600'
              }`}
            >
              Estimate / Quotation
            </button>
          </div>
        </div>

        {/* Salesman Name */}
        <div>
          <label className={`block text-[11px] font-bold mb-1 flex items-center space-x-1 ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>
            <User className={`w-3.5 h-3.5 ${isDark ? 'text-amber-400' : 'text-blue-600'}`} />
            <span>Salesman Name <span className="text-rose-500">*</span></span>
          </label>
          <select
            value={salesmanName}
            onChange={(e) => setSalesmanName(e.target.value)}
            className={`w-full px-2.5 py-1.5 rounded-lg font-bold border outline-hidden ${
              isDark ? 'bg-[#0f172a] border-white/15 text-white' : 'bg-slate-50 border-slate-300 text-slate-900'
            }`}
          >
            <option value="Pooja Sharma (EMP-204)">Pooja Sharma (EMP-204)</option>
            <option value="Ramesh Kulkarni (EMP-101)">Ramesh Kulkarni (EMP-101)</option>
            <option value="Amit Patil (EMP-105)">Amit Patil (EMP-105)</option>
            <option value="Suresh Verma (EMP-202)">Suresh Verma (EMP-202)</option>
            <option value="Showroom Counter Direct">Showroom Counter Direct</option>
          </select>
        </div>

        {/* Customer Name */}
        <div>
          <label className={`block text-[11px] font-bold mb-1 ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>Customer Name</label>
          <input
            type="text"
            value={customerName}
            onChange={(e) => setCustomerName(e.target.value)}
            className={`w-full px-2.5 py-1.5 rounded-lg font-semibold border outline-hidden ${
              isDark ? 'bg-white/5 border-white/15 text-white' : 'bg-slate-50 border-slate-300 text-slate-900'
            }`}
          />
        </div>

        {/* Phone */}
        <div>
          <label className={`block text-[11px] font-bold mb-1 ${isDark ? 'text-slate-300' : 'text-slate-700'}`}>Mobile No</label>
          <input
            type="text"
            value={phone}
            onChange={(e) => setPhone(e.target.value)}
            className={`w-full px-2.5 py-1.5 rounded-lg font-mono border outline-hidden ${
              isDark ? 'bg-white/5 border-white/15 text-white' : 'bg-slate-50 border-slate-300 text-slate-900'
            }`}
          />
        </div>
      </div>

      {/* Barcode Quick Scan Bar */}
      <div className={`border rounded-xl p-3 flex items-center justify-between gap-3 text-xs transition-all ${
        isDark
          ? 'bg-white/5 border-white/10 text-white'
          : 'bg-gradient-to-r from-blue-50 to-sky-50 border border-sky-200 text-slate-900'
      }`}>
        <form onSubmit={handleScanBarcode} className="flex items-center space-x-2 flex-1">
          <Barcode className={`w-5 h-5 ${isDark ? 'text-amber-400' : 'text-blue-600'}`} />
          <input
            type="text"
            placeholder="Scan Tag No / Barcode (e.g. TAG-88201) and press Enter..."
            value={barcodeInput}
            onChange={(e) => setBarcodeInput(e.target.value)}
            className={`flex-1 px-3 py-1.5 rounded-lg font-mono text-xs border outline-hidden ${
              isDark
                ? 'bg-white/5 border-white/15 text-white placeholder-slate-500 focus:border-amber-400'
                : 'bg-white border-slate-300 text-slate-900 placeholder-slate-400 focus:border-blue-500'
            }`}
          />
          <button
            type="submit"
            className={`px-3 py-1.5 font-bold rounded-lg cursor-pointer transition-all ${
              isDark
                ? 'bg-gradient-to-r from-amber-400 to-yellow-500 text-slate-950 font-extrabold hover:from-amber-500 hover:to-yellow-600'
                : 'bg-blue-600 hover:bg-blue-700 text-white'
            }`}
          >
            Add
          </button>
        </form>
        <span className={`text-[11px] hidden sm:inline font-mono ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
          Gold 22K 916: ₹{goldRate.toLocaleString('en-IN')}/g
        </span>
      </div>

      {/* Items Table */}
      <div className={`border rounded-xl p-4 shadow-sm space-y-3 transition-all ${
        isDark ? 'bg-[#0f172a]/90 border-white/10 text-white' : 'bg-white border-slate-200'
      }`}>
        <div className={`overflow-x-auto border rounded-lg ${isDark ? 'border-white/10' : 'border-slate-200'}`}>
          <table className="w-full text-left text-xs border-collapse">
            <thead className={`font-bold border-b ${
              isDark ? 'bg-white/10 text-slate-200 border-white/10' : 'bg-slate-50 text-slate-700 border-slate-200'
            }`}>
              <tr>
                <th className={`p-2.5 border-r w-10 text-center ${isDark ? 'border-white/10' : 'border-slate-200'}`}>#</th>
                <th className={`p-2.5 border-r min-w-[200px] ${isDark ? 'border-white/10' : 'border-slate-200'}`}>Item Description</th>
                <th className={`p-2.5 border-r text-right w-24 ${isDark ? 'border-white/10' : 'border-slate-200'}`}>Gross Wt</th>
                <th className={`p-2.5 border-r text-right w-24 font-bold ${isDark ? 'border-white/10 text-amber-300' : 'border-slate-200 text-blue-800'}`}>Net Wt</th>
                <th className={`p-2.5 border-r text-center w-16 ${isDark ? 'border-white/10' : 'border-slate-200'}`}>Purity</th>
                <th className={`p-2.5 border-r text-right w-24 ${isDark ? 'border-white/10' : 'border-slate-200'}`}>Rate/Gm</th>
                <th className={`p-2.5 border-r text-right w-24 ${isDark ? 'border-white/10' : 'border-slate-200'}`}>Making</th>
                <th className={`p-2.5 border-r text-right w-28 font-bold ${isDark ? 'border-white/10 text-amber-300' : 'border-slate-200 text-slate-900'}`}>Total (₹)</th>
                <th className="p-2.5 text-center w-12">Action</th>
              </tr>
            </thead>
            <tbody className={`divide-y font-mono text-[11px] ${
              isDark ? 'divide-white/10 bg-transparent text-slate-200' : 'divide-slate-200 bg-white'
            }`}>
              {items.map((it, idx) => (
                <tr key={it.id} className={isDark ? 'hover:bg-white/[0.04]' : 'hover:bg-sky-50/30'}>
                  <td className={`p-2.5 border-r text-center ${isDark ? 'border-white/10 text-slate-500' : 'border-slate-200 text-slate-400'}`}>{idx + 1}</td>
                  <td className={`p-2.5 border-r font-sans font-semibold ${isDark ? 'border-white/10 text-white' : 'border-slate-200 text-slate-900'}`}>{it.item_name}</td>
                  <td className={`p-2.5 border-r text-right ${isDark ? 'border-white/10' : 'border-slate-200'}`}>{formatWeight(it.gross_wt)}</td>
                  <td className={`p-2.5 border-r text-right font-bold ${isDark ? 'border-white/10 text-amber-300' : 'border-slate-200 text-blue-800'}`}>{formatWeight(it.net_wt)}</td>
                  <td className={`p-2.5 border-r text-center ${isDark ? 'border-white/10' : 'border-slate-200'}`}>{it.purity}%</td>
                  <td className={`p-2.5 border-r text-right ${isDark ? 'border-white/10' : 'border-slate-200'}`}>₹{it.rate}</td>
                  <td className={`p-2.5 border-r text-right ${isDark ? 'border-white/10' : 'border-slate-200'}`}>{formatCurrency(it.making_amt)}</td>
                  <td className={`p-2.5 border-r text-right font-bold ${isDark ? 'border-white/10 text-amber-300' : 'border-slate-200 text-slate-900'}`}>{formatCurrency(it.total_amt)}</td>
                  <td className="p-2.5 text-center">
                    <button
                      onClick={() => setItems(items.filter((x) => x.id !== it.id))}
                      className="text-rose-500 hover:text-rose-400 p-1 cursor-pointer"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Financial Settlement & Total Summary */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs font-mono">
        {/* Trade-in URD */}
        <div className={`p-4 rounded-xl space-y-2 border transition-all ${
          isDark ? 'bg-white/5 border-white/10 text-white' : 'bg-amber-50/70 border-amber-200'
        }`}>
          <div className={`flex justify-between items-center font-bold font-sans ${
            isDark ? 'text-amber-300' : 'text-amber-900'
          }`}>
            <span className="flex items-center space-x-1">
              <Coins className="w-4 h-4 text-amber-500" />
              <span>Old Gold / URD Credit</span>
            </span>
          </div>
          <div>
            <label className={`block text-[10px] mb-1 ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>Old Gold Exchange Value (₹)</label>
            <input
              type="number"
              value={urdAmount}
              onChange={(e) => setUrdAmount(parseFloat(e.target.value) || 0)}
              className={`w-full px-2.5 py-1.5 rounded-lg text-right font-bold border outline-hidden ${
                isDark
                  ? 'bg-white/5 border-white/15 text-amber-300 focus:border-amber-400'
                  : 'bg-white border-amber-300 text-amber-900'
              }`}
            />
          </div>
        </div>

        {/* Tendered Payments */}
        <div className={`p-4 rounded-xl space-y-2 border transition-all ${
          isDark ? 'bg-white/5 border-white/10 text-white' : 'bg-sky-50/70 border-sky-200'
        }`}>
          <span className={`font-bold font-sans block ${isDark ? 'text-slate-200' : 'text-blue-900'}`}>Customer Tender</span>
          <div className="grid grid-cols-2 gap-2">
            <div>
              <label className={`block text-[10px] mb-1 ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>Cash (₹)</label>
              <input
                type="number"
                value={cashTendered}
                onChange={(e) => setCashTendered(parseFloat(e.target.value) || 0)}
                className={`w-full px-2 py-1 rounded font-right font-bold text-xs border outline-hidden ${
                  isDark ? 'bg-white/5 border-white/15 text-white' : 'bg-white border-slate-300 text-slate-900'
                }`}
              />
            </div>
            <div>
              <label className={`block text-[10px] mb-1 ${isDark ? 'text-slate-400' : 'text-slate-600'}`}>Bank / UPI / Card (₹)</label>
              <input
                type="number"
                value={bankTendered}
                onChange={(e) => setBankTendered(parseFloat(e.target.value) || 0)}
                className={`w-full px-2 py-1 rounded font-right font-bold text-xs border outline-hidden ${
                  isDark ? 'bg-white/5 border-white/15 text-amber-300' : 'bg-white border-slate-300 text-blue-900'
                }`}
              />
            </div>
          </div>
        </div>

        {/* Net Settlement */}
        <div className="bg-gradient-to-br from-blue-700 to-indigo-800 text-white p-4 rounded-xl space-y-2 shadow-md">
          <div className="flex justify-between text-xs">
            <span className="text-blue-200">Subtotal:</span>
            <span>{formatCurrency(subtotal)}</span>
          </div>
          <div className="flex justify-between text-xs">
            <span className="text-blue-200">GST (3%):</span>
            <span>{billMode === 'Tax Invoice' ? formatCurrency(taxes.gstAmt) : '₹0.00 (Exempt)'}</span>
          </div>
          <div className="flex justify-between text-base font-bold border-t border-blue-500/40 pt-1">
            <span>Total Bill:</span>
            <span className="text-amber-300">{formatCurrency(totalBill)}</span>
          </div>
          <div className="flex justify-between text-xs pt-1 border-t border-blue-500/40">
            <span className="text-blue-200">Net Balance Due:</span>
            <span className={`font-bold ${netDue > 0 ? 'text-rose-300' : 'text-emerald-300'}`}>
              {formatCurrency(netDue)}
            </span>
          </div>
        </div>
      </div>

      {/* Grid Settings Modal */}
      <ColumnSettingsModal
        isOpen={showColumnSettings}
        onClose={() => setShowColumnSettings(false)}
        columns={columns}
        onSave={(c) => setColumns(c)}
      />

      {/* Print Voucher Modal */}
      <PrintVoucherModal
        isOpen={showPrint}
        onClose={() => setShowPrint(false)}
        voucherType="Sales Invoice"
        voucherNo={invoiceNo}
        date={invoiceDate}
        partyName={customerName}
        amount={totalBill}
      />

      {/* WhatsApp Share Modal */}
      <WhatsAppShareModal
        isOpen={showWhatsApp}
        onClose={() => setShowWhatsApp(false)}
        recipientName={customerName}
        phone={phone}
        defaultMessage={`Namaste ${customerName}, Thank you for your purchase at Swarna Jewellers. Bill No: ${invoiceNo}, Total: ${formatCurrency(totalBill)}. Attended by Sales Executive: ${salesmanName}.`}
      />

      {/* Field Help Modal */}
      <FieldHelpModal
        isOpen={showHelp}
        onClose={() => setShowHelp(false)}
        screenName="Sales Invoice"
      />
    </div>
  );
};
